<Project>
  <!-- TargetFramework is not available early, Directory.Build.props does not help. -->
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <TargetFramework>net6.0</TargetFramework>
    <BaseIntermediateOutputPath>..\build\$(Configuration)\$(TargetFramework)\obj\</BaseIntermediateOutputPath>
    <BaseOutputPath>..\build\$(Configuration)\$(TargetFramework)\bin\</BaseOutputPath>
  </PropertyGroup>

  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)</IntermediateOutputPath>
    <OutputPath>$(BaseOutputPath)</OutputPath>
    <PublishDir>$(BaseOutputPath)publish</PublishDir>
    <PublishSingleFile>true</PublishSingleFile>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SelfContained>false</SelfContained>
    <UseCurrentRuntimeIdentifier>true</UseCurrentRuntimeIdentifier>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>

  <Target Name="DeletePublish" AfterTargets="Clean">
    <Message Text="Deleting the publish directory: $(PublishDir)" Importance="high" />
    <RemoveDir Directories="$(PublishDir)" />
  </Target>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
